---
# handlers file for setup-apache
- name: start httpd service
  service:
    name: httpd
    state: started
  when: ansible_distribution == "RedHat"
  ignore_errors: yes

- name: start apache2 service
  service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"
  ignore_errors: yes

- name: restart apache
  service:
    name: httpd
    state: restarted
  when: ansible_distribution == "RedHat"
