---
- name: Add Listing TCP port to Firewalld
  hosts: all
  gather_facts: true
  become: true
  tasks:

   - name: change SELinux to Permissive mode
     selinux:
       policy: targeted
       state: permissive


   - name: Open Apache ports in the firewall
     firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
     with_items:
       - "80/tcp"
       - "443/tcp"
       - "389/tcp"
       - "389/udp"
       - "8081/tcp"
       - "8082/tcp"
       - "8080/tcp"

   - name: Ensure HTTPD service is started
     ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

   - name: Restart Firewall Service
     ansible.builtin.service:
        name: firewalld
        state: restarted


