---
- name: Install IDM client
  hosts: 192.168.11.150
  become: true

  #  roles:
  #- role: ipaclient
  #  state: present
   
  tasks: 
  
    - name: Configure Hostname
      ansible.builtin.hostname:
        name: "hostname"
      become: true

      #   - name: Enable EPEL Repo if not enabled on RH8
      #dnf:
      # enablerepo: epel-release
      # state: latest
      # baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      # when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] >= '8'

    - name: Enable EPEL Repo if not enabled on RH9
      dnf:
        name: epel-release
        state: present
      when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] >= '9'

    - name: Update packages using DNF
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Enable dnf module idm:DL1
      ansible.builtin.dnf:
        enablerepo: idm:DL1
        state: present
        
    - name: Enable dnf module distrosync
      ansible.builtin.dnf:
        enablerepo: distrosync
        state: present

    - name: Enable module idmLDL1/client
      ansible.builtin.dnf:
        enablerepo: idm:DL1/client
        state: present

   #- name: Install ipa-client



