- name: install apache and php for Ubuntu servers
  tags: apache,apache2, ubuntu
  apt:
    name:
       - apache2
       - libapache2-mod-php
    state: latest

  become: true
  when: ansible_distribution == "Ubuntu"

- name: install apache and php for RedHat servers
  tags: apache,apache2, redhat
  dnf:
    name:
       - httpd
       - php
    state: latest
  when: ansible_distribution == "RedHat"

- name: start apache (Redhat)
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"

- name: start apache (Ubuntu)
  systemd:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: start memcached
  service:
    name: memcached
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"

- name: copy default html file to site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

