- name: add shh key for simone
  tags: always
  authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDi6H1xfSkY7LdxYsx38r3SSm91+5RCDpvtHIWOhaOFuzURVQlfpadG1SYmmRSw0ejRwAjTOGs6fYn+Dj8IOkFsutF6nh7O5g0ihe2wRfHZSk7reqDbUvRMDK2lWzI38yRTJjpV4aRfI6p22ATk1l0VR6Mr/VW4kef5+sbMP6SfEVlftNDJ5Rov2Vy0bDvHG0RXm2PYBokgKPSYWls1KUKuh5wgD2fhhjRfD55sicLe9k9X89H0gIS2RGie2ZYUDlV4c+FEXipCx5x/PkUw5I9znxMmxGES3gPCFCwEGvZ5Fc3N40t9fQx359JxhthbctJMWTwILEx0DyU42iUbPkPQubLP2NGWDbuuLWgZ30a+n8xuZM5JFs7hBWMlvqBq9Mxu7rwWw9blZZRLVCVAlA4y0q55AblS8UZZEdrZsx9p+q4ywU/lxP3pb9ELbOyGSEey5OVfOQo9ogJh3HyIzB2OGEHj/nfGlcRMpGCmGaJ/knf1AxlOp/xFXjU+e6OBqCWG8vJq1oQrSsZmgnbEfCjuEO6HkQhtJQqZzHZtlTa2ldbPRiBwqJ29JqOetTI+4Hn9h3gq3T0HDKuuiTyC9y1NLXY7jWrLTC5Zrvs+jnasClgkDTdnH2sV8i+1LjZOvYtpxUYFIjHkDK5vB+mOSzVjuxqxPsI5g2T8n0DMxBOPrw== pr26271@gmail.com"

