- name: install mariadb (Redhat)
  tags: redhat,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "RedHat"

- name: install mariadb (Ubuntu)
  tags: ubuntu,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
