- name: install apache and php
  tags: apache,apache2,httpd
  package:
    name:
       - {{ apache_package_name }}
       - {{ php_package_name }}    state: latest

- name: start apache
  service:
    name: {{ apache_service }}
    state: started
    enabled: yes

- name: start apache (Ubuntu)
  systemd:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: start memcached
  service:
    name: memcached
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"

- name: copy default html file to site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

