---

- hosts: all
  become: true
  roles: 
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: app_servers
  become: true
  roles:
    - app_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

